console.log("helloworld");
var names = "Sunny Shahzad yayyy";
var number = 144;
console.log(names + number);
console.log("this is my client for another jobs " + names);
console.log("tsc main.ts -w Conrol + C");
var friends = ["Sunny", "Hamza", "Hammad"];
console.log(friends[0]);
console.log(friends[1]);
console.log(friends);
console.log("tsc --init (initialize)");
