var car = "Lambhorgini";
console.log("is car == 'Lambhorgini'? i predict is true.");
console.log(car == 'Lambhorgini');
console.log("is car == 'carss' ? i predict false");
console.log(car == "carss");
var waari = "Sunny";
console.log("is waari == 'Sunny'? i predict true ");
console.log(waari == "Sunny");
console.log("is sunny == 'Shahzad' ? i predict false");
console.log(waari == 'Shahzad');
var num1 = 8;
console.log("is num1 == 8 ? i predict true");
console.log(num1 == 8);
console.log("is num1 == '9' i predict false");
console.log(num1 == 9);
var num2 = 25;
console.log("is num2 == 25 ? i predict true");
console.log(num2 == 25);
console.log("is num2 == '20' i predict false");
console.log(num2 == 20);
var num3 = 100;
console.log("is num3 == 100 ? i predict true");
console.log(num3 == 100);
console.log("is num3 == '1000000' i predict false");
console.log(num3 == 1000000);
var tallu = "Talha";
console.log("is tallu == 'Talha'? i predict true");
console.log(tallu == "Talha");
console.log("is tallu == 'Tallu'? i predict false");
console.log(tallu == "Tallu");
